package frc.robot.constants;

/**
 * Every hardware address on the robot, in one place.
 *
 * <p>If a number identifies a physical port -- a CAN device, a DIO channel, a PWM channel -- it
 * belongs here and nowhere else. Tuning values go in {@link Constants}; this file answers only
 * "what is plugged in where."
 *
 * <p><b>CAN IDs are unique per bus, not globally.</b> The drivetrain lives on its own CANivore, so
 * drive IDs 1-8 can safely coexist with RIO-bus IDs. Keeping them in separate blocks anyway makes
 * a Phoenix Tuner device list far easier to read.
 *
 * <p><b>Numbering convention</b> -- leave gaps so a mid-season mechanism can be inserted without
 * renumbering anything:
 * <ul>
 *   <li>0-8   drivetrain (CANivore): Pigeon, drive, steer, CANcoders
 *   <li>20-29 intake / ground-level mechanisms
 *   <li>30-39 indexing / handling
 *   <li>40-49 scoring
 *   <li>50-59 superstructure (elevator, arm, wrist)
 * </ul>
 */
public class RobotMap {

  /** Named CAN buses. Never hardcode a bus name as a string literal at a call site. */
  public static class canBusNames {
    /** Drivetrain-only CANivore. Must match the name set in Phoenix Tuner. */
    public static final String CANIVORE = "canivore";
    /** The roboRIO's built-in bus. Everything that is not the drivetrain lives here. */
    public static final String RIO = "rio";
  }

  public static class canIDs {

    /** Generated by Tuner X. If you change these, regenerate TunerConstants.java to match. */
    public static class Drivetrain {
      // Order convention: back left, back right, front left, front right.
      public static final int[] DRIVE = { 1, 2, 3, 4 };
      public static final int[] STEER = { 5, 6, 7, 8 };
      public static final int[] CANCoder = { 1, 2, 3, 4 };

      public static final int GYRO = 0; // Pigeon 2.0
    }

    // -------------------------------------------------------------------------
    // Season mechanisms. Delete the examples and add yours here.
    // -------------------------------------------------------------------------

    public static class ExampleVelocitySubsystem {
      public static final int MOTOR = 20;
      // A follower gets its own CAN ID; see VelocityControlSystem.followMotor().
      public static final int MOTOR_FOLLOWER = 21;
    }

    public static class ExamplePositionSubsystem {
      public static final int MOTOR = 50;
    }
  }

  /** roboRIO digital IO channels -- limit switches, beam breaks, encoders. */
  public static class dio {
    // public static final int EXAMPLE_BEAM_BREAK = 0;
  }

  /** roboRIO PWM channels -- LED strips, servos, non-CAN motor controllers. */
  public static class pwm {
    // LEDConstants.kPort is the addressable LED strip; add servos and the like here.
  }

  private RobotMap() {}
}
